baidu_analytics: e6404c2d3a05f8d5e2064353cfd9d08f
valine:
  enable: false # if you want use valine,please set this value is true
  appId:  cVJSPJ4yyPqjzFhWe2SfQpQh-gzGzoHsz # leancloud application app id
  appKey:  HG4lu3nDxlCuYewgh3EcL5n8 # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: '' # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info